trigger:
- master

jobs:
- job: Windows
  strategy:
    matrix:
      DEBUG:
       buildConfiguration: 'Debug'
      RELEASE:
       buildConfiguration: 'Release'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: echo hello from Windows
  - script: dotnet test --configuration $(buildConfiguration)
- job: macOS
  strategy:
    matrix:
      DEBUG:
       buildConfiguration: 'Debug'
      RELEASE:
       buildConfiguration: 'Release'
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: echo hello from macOS
  - script: dotnet test --configuration $(buildConfiguration)
- job: Linux
  strategy:
    matrix:
      DEBUG:
       buildConfiguration: 'Debug'
      RELEASE:
       buildConfiguration: 'Release'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: echo hello from Linux
  - script: dotnet test --configuration $(buildConfiguration)
